### ISSUE TITLE
use GitHub Actions to build and upload docker images

### ISSUE THREAD

**Issue by haochenx** [kxcteam/pubinfra.dockerfiles#13]
## Notes
- ref: https://github.com/marketplace/actions/build-and-push-docker-images
- tagging convention: https://github.com/kxcteam/pubinfra.dockerfiles/tree/main/ocaml-general

**Comment by haochenx** [comment]
fyi: @kxc-wraikny
tagging convention added to desc

**Comment by kxc-wraikny** [comment]
@haochenx 
Node.js is not installed in the [Dockerfile](https://github.com/kxcteam/pubinfra.dockerfiles/blob/main/ocaml-general/Dockerfile), what does `nodejs-version` mean?

**Comment by kxc-wraikny** [comment]
https://github.com/kxcteam/pubinfra.dockerfiles/blob/8d0f3d4f551b691235189dc8a49db2a1b758bb52/ocaml-general/Dockerfile#L17-L19
I see.

**Comment by kxc-wraikny** [comment]
@haochenx 
Can I specify a Node.js version instead of the latest one?

**Comment by haochenx** [comment]
>Can I specify a Node.js version instead of latest?

yes and actually please. 
pls take the version from a build argument as well. 

At the end, we’d like to have a matrix build of 14, 16, 18 LTSs and latest

**Comment by kxc-wraikny** [comment]
@haochenx 

> ${ocaml-version}
    (hopefully) alias for ubuntu.22.04-ocaml.${ocaml-version}-node.${some-random-version}-amd64

For which Node.js version should ${ocaml-version} tag be set as an alias?

**Comment by haochenx** [comment]
>For which Node.js version should ${ocaml-version} tag be set as an alias?

let's use 18lts @kxc-wraikny
