### ISSUE TITLE
OCaml 5.0.0 compatibility

### ISSUE THREAD

**Issue by kxc-waddlaw** [kxcteam/pubinfra.dockerfiles#19]
The current `Dockerfile` approach requires two Dockerfiles, one for OCaml 4 and one for OCaml 5. (for installing dependencies. See: https://github.com/kxcteam/pubinfra.dockerfiles/pull/17/files)

Therefore, we want to use Docker's "ARG" feature to externally provide OCaml version information and switch installation scripts accordingly. (ref: [Understand how ARG and FROM interact](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact) and [ARG](https://docs.docker.com/engine/reference/builder/#arg))

example:

```shell
$ docker build --build-arg package_install_script_filename=install_ocaml_4_pacakges.sh .
# In this case, we expect that `install_ocaml_4_pacakges.sh` will be called internally.


$ docker build --build-arg package_install_script_filename=install_ocaml_5_pacakges.sh .
# In this case, we expect that `install_ocaml_5_pacakges.sh` will be called internally.
```

**Comment by kxc-wraikny** [comment]
Would it be good to start this issue ( #19 ) after #17 is merged and then continue with #13?

**Comment by haochenx** [comment]
@kxc-wraikny #13 is way more important than #19 so please proceed from #13 first

**Comment by haochenx** [comment]
@kxc-wraikny 
この PR やる時 ↓ PR で追加された GitHub Actions の workflow の validate-ocaml-general ジョブの matrix に ocaml-version = 5.0.0 をいれてほしい
- #20

**Comment by haochenx** [comment]
fyi: @kxc-wraikny @kxc-waddlaw 
desc にあった build-arg を変更しました
